### ISSUE TITLE
NewRus API

### ISSUE THREAD

**Issue by miouser** [technic/iptvdream#14]
некоректно обрабатывается ответ.
начнём с have_archive
этот параметр присутсаует на всех каналах. вот только у одних 
"have_archive":1,  а у других  "have_archive":0,

соотв. "have_archive":0, не имеют архивов, но плагин нам на всех каналах показывает будто-то везде есть архивы
###### 

следущая нестыковка это "protected"
это тоже стандартный параметр присутсвующий у всех каналов и имеет значение "protected":0,

на каналах эротики (исключение НовоеТВ у них ВСЕ каналы с "0") прописано "protected":1, так вот при этом условии, для получения стрима в запросе get_url.php должно содержаться "protect_code=код - внесённый в натройках"

пример
/api/json/get_url.php?&cid=139&protect_code=162306&MWARE_SSID=a153c6be219e4fcfd04bc6c6a876f0f6

**Comment by miouser** [comment]
надо пологать решения ещё нет???
или пожет я непонятно излагаю проблему?

**Comment by technic** [comment]
Если честно, то я пока не смотрел.

**Comment by miouser** [comment]
ок, такой ответ тоже устраивает. :)
а то просто стали брать сомнения.

**Comment by miouser** [comment]
хочу отметить, что NewRusTV "исправили" свою ошибку с откытостью эротических каналов и теперь имеют параметр "protected":1, и соотв. на данный момент их просмотр не возможен так как плагин это дело не обрабатывает. :(

ps: 2.4.0-r0

**Comment by technic** [comment]
2.4.1
Исправлено.

**Comment by miouser** [comment]
проверил,
на сервисе NewRusTV теперь всё как положено.

спасибо!!!
