### ISSUE TITLE
kartinatv_2.3.6-r1 (NewRus)

### ISSUE THREAD

**Issue by miouser** [technic/iptvdream#2]
невозможно запустить сервис NewRus!
при запуске выдаёт ошибку о "No module named pprint"

http://s2.uploads.ru/1V2Sy.png

при попытке включить видеотеку выкидывает зелень. в логе все та же причина  "No module named pprint"

зы: dm800HDse - Enigma2  2012-09-24-tarball - SD skin

**Comment by Alex35** [comment]
Тоже таже проблема! Уже заново имидж поставил и плагин Еклипсе поставил последнюю версию от техника и никак!

**Comment by technic** [comment]
должно быть исправлено

**Comment by miouser** [comment]
оперативно! с 2.3.7-r0 проблемы больше нет.

**Comment by Alex35** [comment]
Да, подтверждаю! Проблемы больше нет! Спасибо!
