### ISSUE TITLE
Новости.

### ISSUE THREAD

**Issue by technic** [technic/iptvdream#3]
## Информация.

версия 2.3.7
исправления ньюрус-тв.

**Comment by technic** [comment]
## Посодействуйте написать инструкцию

Вот версия которая устарела, буду рад если кто то обновит/дополнит. Ещё в качестве помощи новичкам можно сделать видео последней версии плагина с комментариями ))
https://code.google.com/p/kartinatv-dm/wiki/Usage

**Comment by weter71** [comment]
блинн, взялся бы с удовольтсвием, но с русским проблеммы стали, посмотрю, мож видео подготовлю с коментарием.

**Comment by technic** [comment]
### Update

версия 2.3.8
исправления m3u epg.

**Comment by technic** [comment]
### Добавлена ТВтека

Сделал @zakalibit
Пока экспериментально как я понимаю.

**Comment by technic** [comment]
### Добавлены megaimpuls и russiantelek

Спасибо @miouser

**Comment by technic** [comment]
### Update

2.3.9-r4
некоторые исправления.
в том числе epg на newrus.tv

**Comment by technic** [comment]
### Update

2.4.1
Исправлена
эротика и информация о доступности архива на ньрус.
так же обновлен совок-тв на навое апи, спасибо @dremon
и может что то ещё :)

**Comment by weter71** [comment]
не проходит что то у меня с пассом на неврус для еротики

**Comment by miouser** [comment]
@weter71
у меня всё нормально.
установил 2.4.1 поверх 2.3.9
- включил эротику без пароля в настройках - вылезло окно для ввода пароля - ввёл - появилась картинка
- внёс пароль в настройки - выбрал канал - сразу начало показывать 

зы: правда перед этим пару раз зелень вылазила
один раз при рестарте
второй раз когда зашёл в настройки newrus
после перезагрузки больше зелени небыло

**Comment by technic** [comment]
Актуальный плагин на [bitbucket](https://bitbucket.org/iptvdream/iptvdream-4x/).
