### ISSUE TITLE
tvg-name (m3uPlaylist)

### ISSUE THREAD

**Issue by miouser** [technic/iptvdream#5]
не воспринимается название указаное в теге tvg-name

пример 
"#EXTINF:-1 tvg-name="Первый_канал__(Европа)" ,Первый" --- епг нет!

для того чтобы подхватилось епг приходиться прописывать 
"#EXTINF:-1 tvg-name="Первый_канал__(Европа)" ,Первый_канал__(Европа)"

но при этом в списке соотв. канал отображается как "Первый_канал__(Европа)" что не есть красиво.

либо баг либо не доработка

**Comment by technic** [comment]
исправил, ещё добавил url-tvg=http://link-to-jtv.zip

**Comment by miouser** [comment]
да действительно с именами порядок! 

url-tvg
обычно адрес находится в ковычках ;)
живой пример: url-tvg="http://epg.telehouse-ua.net/e/jtvcp1251.zip"

ты забыл или без кавычек реализовано по тех. причинам???

**Comment by technic** [comment]
А вот я качал плейлист и было без кавычек в моем примере.. Хотя по идее твой пример считается за стандарт.
можно такой универсальный взять regexp, одинарных кавычек не бывает надеюсь.
#EXTM3U._\surl-tvg="?([^\s^"]_)

**Comment by miouser** [comment]
ок, теперь ясно из чего исходил.

попутный вопрос (пополнение знаний) с rar архивами можно подружить.
просто у одного провайдера встретил в таком виде url-tvg="http://www.gotview.ru/programs/tv.rar"

**Comment by technic** [comment]
я запускаю консольную команду unzip. Не знаю есть ли для дрима но unrar на Linux тоже не проблема.

**Comment by technic** [comment]
Теперь епг распознает и в кавычках.
