### ISSUE TITLE
полная программа передач (m3uPlaylist) 

### ISSUE THREAD

**Issue by miouser** [technic/iptvdream#6]
возможно ли реализовать чтобы по кнопке info отображалася весь список передач выбраного канала?
а не только в инфобаре (текущая и следущая)

**Comment by technic** [comment]
Не понял а разве сейчас не так ?
а наверное там баг.

**Comment by miouser** [comment]
нет к сожелению не так
<a href="http://s2.uploads.ru/jZtKp.png"><img src="http://s2.uploads.ru/t/jZtKp.png" border="0" /></a> <a href="http://s2.uploads.ru/7v9zq.png"><img src="http://s2.uploads.ru/t/7v9zq.png" border="0" /></a>

**Comment by technic** [comment]
исправлено 2.3.8

**Comment by maigais** [comment]
а где можна видеть поправки 
там невижу https://github.com/technic/iptvdream/commits/develop

**Comment by technic** [comment]
закинул

**Comment by miouser** [comment]
класс!!! проблема решена
спасибо!
<a href="http://s3.uploads.ru/6SH53.png"><img src="http://s3.uploads.ru/t/6SH53.png" border="0" /></a> <a href="http://s3.uploads.ru/obNw3.png"><img src="http://s3.uploads.ru/t/obNw3.png" border="0" /></a>
