### ISSUE TITLE
Проблема заинсталирывать плагин.

### ISSUE THREAD

**Issue by Artemscheck** [technic/iptvdream#7]
Technic, помоги пожалуйста ! У меня дримбокс 800се, имедж опенпли 3.0, кернель 3.2, енигма 2012-12-01,
Проблема, хочу поставить плагин отсюда : ftp://technic.dyndns.org/newrus/, но ни один кроме последниго не инсталируются: пишет 0 ошибок , 0 инсталирт !
на Последнем инсталируется, после рестарта не показывает в меню, заходишь в плагины, сразу писчет : некоторые плагинов нет: Extensions/Kartina TV ( Bad magic number in / usr/lib/enigma2/python/plugins/extensions/kartina tv/_init_.pyo ) !!! Что не правильно , я новый в этом деле.

пробывал эти плагины первые : 2.4 all.ipk и 3.0 all ipk они идут и инсталируются , но таm надо рестартовать когда выходешь заходишь !
помоги в чём проблема ?

**Comment by technic** [comment]
А какое окончание обычно у пакетов openpli ? _mipsel.ipk вот так ?
разкидай вручную файлы умеешь ? У тебя питон 2.7 поэтому нужен mips32el..

Или через telnet может есть опция --force при установке.

**Comment by Artemscheck** [comment]
нет не умею. в смысле окончание опенпли ? где смотреть ? я захожу через filezilla, стераю картину тв , рестарт, юсб взаде вставляю, потом инсталирую.

**Comment by technic** [comment]
попробуй по ftp в /etc/opkg.conf прописать
arch mips32el 300

и ставить newrus плагин с окончанием mips32el.ipk, Ну такое окончание у имени файла.
Или может /etc/opkg/opkg.conf проверить сейчас не могу как точно называется.

**Comment by Artemscheck** [comment]
просто в конце строки прописать ? и потом плагин заинсталирывать ?

**Comment by technic** [comment]
Покажи что в том файле у тебя

да дописать новой строкой в конец
и ставить.

**Comment by Artemscheck** [comment]
```

# Must have one or more source entries of the form:
#
#   src <src-name> <source-url>
#
# and one or more destination entries of the form:
#
#   dest <dest-name> <target-path>
#
# where <src-name> and <dest-names> are identifiers that
# should match [a-zA-Z0-9._-]+, <source-url> should be a
# URL that points to a directory containing a Familiar
# Packages file, and <target-path> should be a directory
# that exists on the target system.

# Proxy Support
#option http_proxy http://proxy.tld:3128
#option ftp_proxy http://proxy.tld:3128
#option proxy_username <username>
#option proxy_password <password>

# Enable GPGME signature
# option check_signature 1

# Offline mode (for use in constructing flash images offline)
#option offline_root target

dest root /
lists_dir ext /var/lib/opkg

arch 
```

**Comment by Artemscheck** [comment]
зделал вот так:

```
# Must have one or more source entries of the form:
#
#   src <src-name> <source-url>
#
# and one or more destination entries of the form:
#
#   dest <dest-name> <target-path>
#
# where <src-name> and <dest-names> are identifiers that
# should match [a-zA-Z0-9._-]+, <source-url> should be a
# URL that points to a directory containing a Familiar
# Packages file, and <target-path> should be a directory
# that exists on the target system.

# Proxy Support
#option http_proxy http://proxy.tld:3128
#option ftp_proxy http://proxy.tld:3128
#option proxy_username <username>
#option proxy_password <password>

# Enable GPGME signature
# option check_signature 1

# Offline mode (for use in constructing flash images offline)
#option offline_root target

dest root /
lists_dir ext /var/lib/opkg

arch mips32el 300
```

**Comment by maigais** [comment]
папробуи так
для ночало устонови json
ано попалнение к плагу newrustv

работаеш с DCC_E2  
телнетом 

```

opkg update && opkg install python-json
```

 далие закинь плагин  ftp://techhost.dlinkddns.com/newrus/enigma2-plugin-extensions-newrustv_2.3.7-r1_mips32el.ipk
 в /tmp

далие опять телнетом

```
cd /tmp
```

```
opkg install enigma2-plugin-extensions-newrustv_2.3.7-r1_mips32el.ipk
```

 (enter) и перегруз рессивера

**Comment by technic** [comment]
Такие кавычки надо делать. Чтобы копировать файл сюда какой то

``````
```
что-то 
```
``````

**Comment by technic** [comment]
@Artemscheck получилось в итоге ?

**Comment by technic** [comment]
Закрываю
