### ISSUE TITLE
NewRusTV не обновляет EPG

### ISSUE THREAD

**Issue by amd93** [technic/iptvdream#8]
при включении NewRusTV (версия kartina_tv.2.3.8) EPG показывается на всех каналах без проблем.

после какого-то времени, а именно переключении каналов (можно и просто только один канал смотреть), EPG у некоторых пропадает.

когда заходишь на канал - EPG показывается только в Info баре.

в чем может быть проблема?

c m3uPlaylist ещё как то не разобрался. (не знаю как его создавать и чего прописывать).

**Comment by amd93** [comment]
перезагрузка энигмы помогает недолго - опять через какое то время исчезает....

P.S. насчет m3uPlaylist - нужен ли отдельный issue? проблема то в том - не знаю как определить адрес (IP) потока и как правильно прописать....

**Comment by amd93** [comment]
а все понял:-) провайдеру iptv написал:-) буду ждать ответа..

но проблема с EPG все равно остается открытой.

**Comment by technic** [comment]
кривое апи ньюрус, попробую выкрутиться

**Comment by amd93** [comment]
Ок. буду ждать:-) спасибо.

**Comment by technic** [comment]
Исправил 3e2f900

**Comment by amd93** [comment]
спасибо большое. проблема исправлена, все работает
